
services:
    title: "About Noël"
    text: "I’m a researcher, writer, and educator originally from Sacramento, CA. I’m currently pursuing a PhD at Boston College in English, where I explore twentieth- and twenty-first American literature and culture, feminist and gender theory, disability studies, and medical and health humanities. Prior to my doctoral work, I taught extensively at the secondary level in the Los Angeles area, designing interdisciplinary, project-based curricula for a variety of humanities courses. I hold a MA in American Studies from  Pepperdine University and a BA in psychology with a minor in English from the University of California at Davis. I received my teaching certification from Loyola Marymount University through the LMU | Teach For America Partnership and hold clear CA teaching credentials in English, art, and Career and Technical Education with an emphasis on Marketing, Sales, and Service."
  
timeline:
    title: "Recent Work" 
    text: "Lorem ipsum timeline"
    section: timeline
    # left is the default
    #start_align: "left"
    events:
      - title: "Our Humble Beginnings"
        year: "2009-2011"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
        image: assets/img/timeline/1.jpg
        alt: 
      - title: "An Agency is Born"
        year: "March 2011"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
        image: assets/img/timeline/2.jpg
        alt: 
      - title: "Jekyll Theme is created"
        year: "2019"
        desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
        image: assets/img/timeline/3.jpg
        alt: image alt text
      - title: "Title"
        year: "2009-2011"
        desc: "Your description here, **Markdown** is fully supported."
        image: assets/img/timeline/4.jpg
        alt: 
        # you can enforce the aligment
        align: right
    end: "Be Part <br> of Our <br> Story!"
    
portfolio:
    title: "Teaching"
    text: "In my seven years as a secondary educator, I’ve worked exclusively with high-need populations; every teaching position I’ve held has been at a Title 1 school, meaning that the school served a high concentration of families with low socioeconomic status. I’m well-versed in teaching strategies and methodology for students with diverse needs, including English Language Learners and students with disabilities. I love collaboration and interdisciplinary course design."
    section: portfolio
    closebutton: "Close Project"
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com/neingramm
        icon: "fab fa-twitter"  
      - url: https://www.linkedin.com/in/no%C3%ABl-ingram-10613435/
        icon: "fab fa-linkedin-in"
      - url: https://github.com/neingram
        icon: "fab fa-github"
   


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
